path: /home/eligijus/projects/yolo-segmentation-example/datasets  # dataset root dir
train: images/train  # train images (relative to 'path') 4 images
val: images/val  # val images (relative to 'path') 4 images

# Classes
names:
  0: puddle
  1: greenery

# The bellow is left just for the example; In the machine this code was created
# there were 4 experiments run
model_to_use: runs/segment/train9/weights/best.pt

# Class coloring table (for visualization)
color_map: 
  0: blue
  1: greenery

# Label remapper 
label_remapper: 
  1: 0
  2: 1